made newPage functions to work without arguments too
justvanrossum/drawbot-skia pull request #14
Opened 2021-03-18 20:40 UTC by jansindl3r

I made the `newPage` function to work without arguments too. 

```
    Initial newPage() without arguments: 1000 x 1000
    Second newPage() without arguments: same as previous page
```

I found an issue that the function throws an error if you don't draw before. Probably because RecordingDocument's `        self.pageWidth = self.pageHeight = None` Drawing makes it somehow become not None. It got a temporary fix

2021-03-18 20:45 UTC, jansindl3r commented
btw, all test that test Image failed even with fresh copy

2021-03-19 08:31 UTC, justvanrossum commented
The test failure is because of a reather agggressive linter setting. Please check with

`$ flake8 --max-line-length=127 path/to/file.py`

...for both files you're edting. If that passes, run pytest locally. Doing

`$ pytest`

should be enough. If that passes, there's a good chance the CI will pass, too.

2021-03-19 08:42 UTC, justvanrossum requested changes

2021-03-19 08:42 UTC, justvanrossum commented on src/drawbot_skia/drawing.py
> +    def newPage(self, *dimensions):
Please write it like this:
```python
def newPage(self, width=None, height=None):
```
And check wether either both are None or neither.

2021-03-19 08:42 UTC, justvanrossum commented on tests/test_api.py
> +        )
Please also check that calling `newPage(123)` and `newPage(height=123)` raise errors.

```python
with pytest.raises(...):
    ...code that should raise an exception...
```

2021-03-19 08:42 UTC, justvanrossum commented on src/drawbot_skia/drawing.py
> +        assert len(dimensions) in (0, 2), (
This is an api entry point, and wrong arguments should raise an proper exception. In this case: TypeError is the right exception.

2021-03-19 08:42 UTC, justvanrossum commented on src/drawbot_skia/drawing.py
> +                height = default_canvas_dimensions[1]
You can write: 
```python
   width, height = default_canvas_dimensions
```

2021-03-19 08:42 UTC, justvanrossum commented on tests/test_api.py
> +    assert (db.width(), db.height()) == default_canvas_dimensions, (
assert messages aren't really needed in test asserts

2021-03-19 08:42 UTC, justvanrossum commented on tests/test_api.py
> +    assert (db.width(), db.height()) == default_canvas_dimensions, (
I mean, writing this
```python
assert (db.width(), db.height()) == default_canvas_dimensions
```
is enough

2021-03-19 08:42 UTC, justvanrossum commented on tests/test_api.py
> +def test_newPage_dimensions_arguments():
Please add one more blank line before (this is a flake8 linter error)

2021-03-19 08:42 UTC, justvanrossum commented on src/drawbot_skia/drawing.py
> +default_canvas_dimensions = (1000, 1000)
Please add another blank line before and after.

2021-03-19 16:30 UTC, justvanrossum requested changes

2021-03-19 16:30 UTC, justvanrossum commented on src/drawbot_skia/drawing.py
> +        if width and not height or height and not width:
```suggestion
        if (width is not None and height is None) or (height is not None and width is None):
```

2021-03-19 16:30 UTC, justvanrossum commented on src/drawbot_skia/drawing.py
> +        if not width and not height:
```suggestion
        if width is None and height is None:
```

2021-03-19 16:30 UTC, justvanrossum commented on src/drawbot_skia/drawing.py
> +            if not width or not height:
```suggestion
            if width is None or height is None:
```

2021-03-19 17:38 UTC, justvanrossum approved these changes

2021-03-19 17:41 UTC, merged

2021-03-19 17:41 UTC, justvanrossum commented
Thanks Jan!

2021-03-19 18:42 UTC, jansindl3r commented
I learnt something again :) I thank you! 

I am making a small python workshop soon and it's great to welcome a few Windows users too. VS code setup with split editor where one half shows the exported image works pretty well as a substitution for DrawBot app. 

Though sharing install instructions with 13 steps is not that good for beginners, but they managed!