Implement PointPen behaviour for BezierPath()
justvanrossum/drawbot-skia pull request #9
Opened 2020-10-09 19:16 UTC by jenskutilek

Per the DrawBot docs, a BezierPath can be used like a PointPen. I tried to implement it and it seems to work, but I'm not sure that's all there's to it ;)

2020-10-09 19:22 UTC, justvanrossum commented
Hm, I don't like the multiple inheritance and I don't like the circular reference that never gets broken. Let me think.

2020-10-09 19:28 UTC, justvanrossum commented
Have a look at what DB does:

https://github.com/typemytype/drawbot/blob/f96bb7fb26ec2163fa5400ee2c38676b7af6f6bb/drawBot/context/baseContext.py#L221-L227

It uses a temporary PointToSegmentPen that gets removed at `endPath()`.

2020-10-12 20:04 UTC, jenskutilek commented
Of course! I should have checked the drawBot code in the first place.

2020-10-13 08:29 UTC, justvanrossum requested changes
Thanks! Apart from one nit, this looks good.

2020-10-13 08:29 UTC, justvanrossum commented on src/drawbot_skia/path.py
>      def _endPath(self):
This needs to become `endPath(self):`
```suggestion
    def endPath(self):
```

2020-10-13 08:53 UTC, justvanrossum approved these changes

2020-10-13 08:54 UTC, merged